// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider_auth_state.proto

package oidc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// that gives the cookie..
//message StateCookieValue {
type StateEnvelope struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateEnvelope) Reset()         { *m = StateEnvelope{} }
func (m *StateEnvelope) String() string { return proto.CompactTextString(m) }
func (*StateEnvelope) ProtoMessage()    {}
func (*StateEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9489a82fc56e6c, []int{0}
}

func (m *StateEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateEnvelope.Unmarshal(m, b)
}
func (m *StateEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateEnvelope.Marshal(b, m, deterministic)
}
func (m *StateEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateEnvelope.Merge(m, src)
}
func (m *StateEnvelope) XXX_Size() int {
	return xxx_messageInfo_StateEnvelope.Size(m)
}
func (m *StateEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_StateEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_StateEnvelope proto.InternalMessageInfo

func (m *StateEnvelope) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *StateEnvelope) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *StateEnvelope) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *StateEnvelope) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// that give the envelope payload
//message StateValue {
type StateData struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Userdata             []byte   `protobuf:"bytes,3,opt,name=userdata,proto3" json:"userdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateData) Reset()         { *m = StateData{} }
func (m *StateData) String() string { return proto.CompactTextString(m) }
func (*StateData) ProtoMessage()    {}
func (*StateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9489a82fc56e6c, []int{1}
}

func (m *StateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateData.Unmarshal(m, b)
}
func (m *StateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateData.Marshal(b, m, deterministic)
}
func (m *StateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateData.Merge(m, src)
}
func (m *StateData) XXX_Size() int {
	return xxx_messageInfo_StateData.Size(m)
}
func (m *StateData) XXX_DiscardUnknown() {
	xxx_messageInfo_StateData.DiscardUnknown(m)
}

var xxx_messageInfo_StateData proto.InternalMessageInfo

func (m *StateData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StateData) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *StateData) GetUserdata() []byte {
	if m != nil {
		return m.Userdata
	}
	return nil
}

func init() {
	proto.RegisterType((*StateEnvelope)(nil), "oidc.StateEnvelope")
	proto.RegisterType((*StateData)(nil), "oidc.StateData")
}

func init() { proto.RegisterFile("provider_auth_state.proto", fileDescriptor_db9489a82fc56e6c) }

var fileDescriptor_db9489a82fc56e6c = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xbb, 0xae, 0x82, 0x40,
	0x10, 0x86, 0xc3, 0xe5, 0x9c, 0x03, 0x93, 0x63, 0xb3, 0xb1, 0x58, 0x89, 0x05, 0xa1, 0xa2, 0xb2,
	0xf1, 0x15, 0xf4, 0x05, 0xb0, 0xb4, 0x20, 0x23, 0xbb, 0x89, 0x24, 0xc0, 0x6c, 0x76, 0x07, 0x12,
	0xdf, 0xde, 0xb8, 0x72, 0xe9, 0xe6, 0xfb, 0x92, 0xf9, 0xff, 0x19, 0x38, 0x18, 0x4b, 0x53, 0xab,
	0xb4, 0xad, 0x71, 0xe4, 0x67, 0xed, 0x18, 0x59, 0x9f, 0x8c, 0x25, 0x26, 0x11, 0x53, 0xab, 0x9a,
	0x82, 0x60, 0x77, 0xfb, 0xc8, 0xeb, 0x30, 0xe9, 0x8e, 0x8c, 0x16, 0x19, 0x24, 0xcb, 0x8e, 0x0c,
	0xf2, 0xa0, 0x4c, 0xab, 0x95, 0x85, 0x80, 0xd8, 0x61, 0xc7, 0x32, 0xcc, 0x83, 0xf2, 0xbf, 0xf2,
	0xb3, 0xd8, 0xc3, 0xcf, 0x40, 0x43, 0xa3, 0x65, 0xe4, 0xe5, 0x17, 0x84, 0x84, 0x3f, 0x83, 0xaf,
	0x8e, 0x50, 0xc9, 0xd8, 0xfb, 0x05, 0x8b, 0x3b, 0xa4, 0xbe, 0xf0, 0x82, 0x8c, 0xe2, 0x08, 0x29,
	0xb7, 0xbd, 0x76, 0x8c, 0xbd, 0xf1, 0x6d, 0x51, 0xb5, 0x89, 0x2d, 0x3a, 0xf4, 0x77, 0xcc, 0xd1,
	0x19, 0x24, 0xa3, 0xd3, 0x56, 0x21, 0xe3, 0xdc, 0xb9, 0xf2, 0xe3, 0xd7, 0xbf, 0x76, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x2a, 0x91, 0xfa, 0x93, 0xf7, 0x00, 0x00, 0x00,
}
