// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state.proto

package state

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// that gives the cookie..
//message StateCookieValue {
type Envelope struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{0}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Envelope) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *Envelope) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Envelope) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// that give the envelope payload
//message StateValue {
type Data struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Userdata             []byte   `protobuf:"bytes,3,opt,name=userdata,proto3" json:"userdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{1}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Data) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Data) GetUserdata() []byte {
	if m != nil {
		return m.Userdata
	}
	return nil
}

func init() {
	proto.RegisterType((*Envelope)(nil), "state.Envelope")
	proto.RegisterType((*Data)(nil), "state.Data")
}

func init() { proto.RegisterFile("state.proto", fileDescriptor_a888679467bb7853) }

var fileDescriptor_a888679467bb7853 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xbd, 0xae, 0x82, 0x40,
	0x10, 0x85, 0xc3, 0xdf, 0xbd, 0x30, 0x5a, 0x4d, 0x2c, 0x36, 0xc4, 0x82, 0x50, 0x51, 0xd9, 0xf8,
	0x0a, 0xfa, 0x02, 0x14, 0xf6, 0xa3, 0x4c, 0x81, 0x01, 0x76, 0xb3, 0x3b, 0x92, 0xf8, 0xf6, 0x26,
	0x23, 0x42, 0x37, 0xdf, 0x57, 0x9c, 0x33, 0x07, 0x76, 0x41, 0x48, 0xf8, 0xe4, 0xbc, 0x15, 0x8b,
	0x99, 0x42, 0xfd, 0x84, 0xfc, 0x3a, 0xcd, 0x3c, 0x58, 0xc7, 0x58, 0x42, 0xee, 0xbc, 0x9d, 0xfb,
	0x8e, 0xbd, 0x89, 0xaa, 0xa8, 0x29, 0xda, 0x95, 0x11, 0x21, 0x0d, 0x34, 0x88, 0x89, 0xab, 0xa8,
	0xd9, 0xb7, 0x7a, 0xe3, 0x01, 0xb2, 0xc9, 0x4e, 0x0f, 0x36, 0x89, 0xca, 0x2f, 0xa0, 0x81, 0x7f,
	0x47, 0xef, 0xc1, 0x52, 0x67, 0x52, 0xf5, 0x3f, 0xac, 0x6f, 0x90, 0x5e, 0x48, 0x08, 0x8f, 0x50,
	0x48, 0x3f, 0x72, 0x10, 0x1a, 0x9d, 0x16, 0x25, 0xed, 0x26, 0xb6, 0xd4, 0x58, 0x5f, 0x58, 0x52,
	0x4b, 0xc8, 0x5f, 0x81, 0x7d, 0x47, 0x42, 0x4b, 0xdd, 0xca, 0xf7, 0x3f, 0x5d, 0x74, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x71, 0xb3, 0xef, 0xb8, 0xe0, 0x00, 0x00, 0x00,
}
